name        "aws_opsworks_users"
description "Manage AWS OpsWorks users. Handle SSH keys, terminate sessions, manage home dirs."
maintainer  "AWS OpsWorks"
license     "Apache 2.0"
version     "1.0.0"
